# Generated by Django 6.0.3 on 2026-04-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoExito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('empresa', 'Empresas'), ('institucion', 'Instituciones'), ('coaching', 'Coaching Personalizado')], max_length=20)),
                ('cliente', models.CharField(max_length=100)),
                ('problema', models.TextField()),
                ('capacitacion', models.TextField()),
                ('resultado', models.TextField()),
                ('testimonio', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='trayectoria/')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CasoExitoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='trayectoria/galeria/')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='trayectoria.casoexito')),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
    ]
